dependencies:
 - OpenZeppelin/openzeppelin-contracts@3.1.0
compiler:
 solc:
  remappings:
    - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0'

    
networks:
  default: mainnet-fork
  goerli:
    verify: True
  mainnet-fork:
    verify: False
  development:
    verify: False
dotenv: .env
wallets:
  from_key: ${TESTNET_PRIVATE_KEY}
keys:
  COINMARKETCAP_API_KEY: ${COINMARKETCAP_KEY}