dependencies:
 - OpenZeppelin/openzeppelin-contracts@3.1.0
compiler:
 solc:
  remappings:
    - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0'
  
dotenv: .env  
networks:
  default: mainnet-fork
  goerli:
    wallet: ${GOERLI_PRIVATE_KEY}
    endpoint: ${TESTNET_ALCHEMY_ENDPOINT}
    verify: True
  mainnet-fork:
    verify: False
  development:
    verify: False
wallets:
  from_key: ${TESTNET_PRIVATE_KEY}
keys:
  COINMARKETCAP_API_KEY: ${COINMARKETCAP_KEY}